# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RyanAirBookingsTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RyanAirBookingsTest
  pod 'R.swift'
  pod 'Alamofire'
  pod 'SVProgressHUD', '~> 2.2.2'
  
  target 'RyanAirBookingsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RyanAirBookingsTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
