//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `trip.json`.
    static let tripJson = Rswift.FileResource(bundle: R.hostingBundle, name: "trip", pathExtension: "json")
    
    /// `bundle.url(forResource: "trip", withExtension: "json")`
    static func tripJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.tripJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `Cell`.
    static let cell: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "Cell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 1 view controllers.
  struct segue {
    /// This struct is generated for `TripTableViewController`, and contains static references to 2 segues.
    struct ryanAirBookingsTestTripTableViewController {
      /// Segue identifier `searchView`.
      static let searchView: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, RyanAirBookingsTest.TripTableViewController, SearchControllerTableViewController> = Rswift.StoryboardSegueIdentifier(identifier: "searchView")
      /// Segue identifier `showResults`.
      static let showResults: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, RyanAirBookingsTest.TripTableViewController, RyanAirBookingsTest.ResultsTableViewController> = Rswift.StoryboardSegueIdentifier(identifier: "showResults")
      
      /// Optionally returns a typed version of segue `searchView`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func searchView(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, RyanAirBookingsTest.TripTableViewController, SearchControllerTableViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.ryanAirBookingsTestTripTableViewController.searchView, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `showResults`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func showResults(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, RyanAirBookingsTest.TripTableViewController, RyanAirBookingsTest.ResultsTableViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.ryanAirBookingsTestTripTableViewController.showResults, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      let searchController = StoryboardViewControllerResource<SearchControllerTableViewController>(identifier: "searchController")
      
      func searchController(_: Void = ()) -> SearchControllerTableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: searchController)
      }
      
      static func validate() throws {
        if _R.storyboard.main().searchController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'searchController' could not be loaded from storyboard 'Main' as 'SearchControllerTableViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
